In [1]:
import numpy as np
import matplotlib.pyplot as plt

# 1. Обратная матрица единичной матрицы

In [4]:
e = np.eye(5)
inv_e = np.linalg.inv(e)
print(inv_e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# 5.2. Определитель матрицы

In [7]:
mat = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
print(mat)
print(f'det = {np.linalg.det(mat)}')

[[1 2 3]
 [4 0 6]
 [7 8 9]]
det = 59.999999999999986


# 5.3. Обратная матрица

In [8]:
mat = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
print(mat)
print(f'inv:\n{np.linalg.inv(mat)}')

[[1 2 3]
 [4 0 6]
 [7 8 9]]
inv:
[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


# 5.4 Скалярное произведение векторов

In [9]:
a = np.array([1, 5])
b = np.array([2, 8])
print(np.dot(a, b))

42


# 5.5 Смешанное произведение векторов

In [11]:
a = np.array([1, 5, 0])
b = np.array([2, 8, 7])
c = np.array([7, 1.5, 3])

mixed_mul = np.dot(np.cross(a, b), c)
print(f'Смешанное произведение: {mixed_mul}')

Смешанное произведение: 228.5
